import { Navbar } from '@/components/Navbar';
import { Footer } from '@/components/Footer';
import { motion } from 'framer-motion';
import { FileText, Shield, ScrollText } from 'lucide-react';

export default function Terms() {
    return (
        <div className="min-h-screen flex flex-col bg-slate-50">
            <Navbar />

            <main className="flex-1 pt-24 pb-16">
                <div className="container mx-auto px-4 md:px-6 lg:px-8 max-w-5xl">
                    {/* Header */}
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="text-center mb-12"
                    >
                        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-[#005081]/10 border border-[#005081]/20 text-[#005081] text-sm font-bold uppercase tracking-wider mb-6">
                            <FileText className="w-4 h-4" />
                            Legal Document
                        </div>
                        <h1 className="text-4xl md:text-5xl font-bold text-slate-900 mb-4">Terms & Conditions</h1>
                        <p className="text-lg text-slate-600">Lohakart Terms of Use</p>
                        <p className="text-sm text-slate-500 mt-2">Last Updated: January 2026</p>
                    </motion.div>

                    {/* Content */}
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: 0.2 }}
                        className="bg-white rounded-2xl shadow-lg border border-slate-200 p-8 md:p-12"
                    >
                        <div className="prose prose-slate max-w-none">
                            {/* Introduction */}
                            <div className="mb-8 p-6 bg-slate-50 rounded-xl border-l-4 border-[#005081]">
                                <p className="text-sm leading-relaxed text-slate-700">
                                    This document contains terms and conditions ("Terms/Terms of Use"), and is an electronic record in terms of Information Technology Act, 2000 ("IT Act") and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the IT Act. Further, this electronic record is generated by a computer system and does not require any physical or digital signatures. This electronic record is published in accordance with the relevant provisions of the IT Act. This document is published in accordance with the provisions of Rule 3 (1) of the IT Act (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of the Platform.
                                </p>
                            </div>

                            {/* 1. GENERAL */}
                            <section className="mb-10">
                                <h2 className="text-2xl font-bold text-slate-900 mb-6 flex items-center gap-3">
                                    <span className="flex items-center justify-center w-8 h-8 rounded-lg bg-[#005081] text-white text-sm font-bold">1</span>
                                    GENERAL
                                </h2>

                                <div className="space-y-6">
                                    <div>
                                        <h3 className="font-bold text-slate-800 mb-2">1.1</h3>
                                        <p className="text-slate-700 leading-relaxed">
                                            The platform is owned, managed and operated by <strong>Indiium Ventures Private Limited</strong>, a private limited company duly incorporated under the provisions of the Companies Act, 2013 and having its registered office at Levana Cyber Heights, 10 floor, TCG 2/2 & 5/5, Vibhuti Khand, Gomti Nagar, Lucknow, Uttar Pradesh 226010, India ("Lohakart", "Company", "We", "Us", or "Our").
                                        </p>
                                    </div>

                                    <div>
                                        <h3 className="font-bold text-slate-800 mb-2">1.2</h3>
                                        <p className="text-slate-700 leading-relaxed">
                                            For the purpose of these Terms, wherever the context so requires the term "You", "you" "Your", "your", or "User", shall mean any person who visits, uses or accesses the domain name <a href="https://www.lohakart.com" className="text-[#be1800] hover:underline">https://www.lohakart.com</a> ("Website"), including the related mobile site and mobile application or avails Services (as defined below) or deals with Lohakart in any manner including but not limited to selling or buying materials to or from Lohakart.
                                        </p>
                                    </div>

                                    <div>
                                        <h3 className="font-bold text-slate-800 mb-2">1.3</h3>
                                        <p className="text-slate-700 leading-relaxed">
                                            Lohakart is engaged in the business of facilitating sale and purchase of metal and related merchandise and providing services by to Users registered with the Company or Users availing any facilities provided/offered by Lohakart ("Services"). We are not responsible for the behavior, actions or inactions, accuracy, efficiency of any User, quality of service or product which you may use or procure through us or otherwise.
                                        </p>
                                    </div>

                                    <div>
                                        <h3 className="font-bold text-slate-800 mb-2">1.4</h3>
                                        <p className="text-slate-700 leading-relaxed">
                                            When You use or avail of any of the services provided by Us including but not limited to Services provided through the Platform, You will be subject to the rules, guidelines, policies, terms, and conditions applicable to such service, and they shall be deemed to be incorporated into this Terms of Use and shall be considered as part and parcel of this Terms of Use.
                                        </p>
                                    </div>

                                    <div className="p-4 bg-amber-50 border-l-4 border-amber-500 rounded-r-lg">
                                        <p className="text-sm font-bold text-amber-900 mb-2">IMPORTANT NOTICE</p>
                                        <p className="text-sm text-amber-800 leading-relaxed">
                                            AVAILING SERVICES OFFERED BY LOHAKART, PURCHASING PRODUCTS OFFERED BY LOHAKART, ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE. BY ACCEPTING THESE TERMS, YOU ALSO ACCEPT AND AGREE TO BE BOUND BY LOHAKART POLICIES. IN CASE YOU DO NOT AGREE WITH THESE TERMS, THEN PLEASE REFRAIN FROM USING AND ACCESSING THE PLATFORM.
                                        </p>
                                    </div>
                                </div>
                            </section>

                            {/* 2. CREATING AN ACCOUNT */}
                            <section className="mb-10">
                                <h2 className="text-2xl font-bold text-slate-900 mb-6 flex items-center gap-3">
                                    <span className="flex items-center justify-center w-8 h-8 rounded-lg bg-[#005081] text-white text-sm font-bold">2</span>
                                    CREATING AN ACCOUNT
                                </h2>

                                <div className="space-y-6">
                                    <div>
                                        <h3 className="font-bold text-slate-800 mb-2">2.1</h3>
                                        <p className="text-slate-700 leading-relaxed">
                                            In order to avail the Services, the User is required to create a user account ("Account") on the Platform and become a registered user ("Registered User"). Transaction on the Platform is available only to persons who can form legally binding contracts under Indian Contract Act, 1872. <strong>If you are a minor i.e., under the age of 18 years, you may use the Platform only under the supervision and prior consent/permission of a parent or legal guardian.</strong>
                                        </p>
                                    </div>

                                    <div>
                                        <h3 className="font-bold text-slate-800 mb-2">2.2</h3>
                                        <p className="text-slate-700 leading-relaxed">
                                            To create an Account, a User is required to provide information including but not limited to name, User ID, gender, address, ZIP/postal code, age, phone number, password, entity details, GST number etc.
                                        </p>
                                    </div>

                                    <div>
                                        <h3 className="font-bold text-slate-800 mb-2">2.3</h3>
                                        <p className="text-slate-700 leading-relaxed">
                                            You shall be responsible for maintaining the confidentiality of your Display Name and Password and You shall be responsible for all activities that occur under your Display Name and Password. Your mobile phone number and/or e-mail address is treated as Your primary identifier on the Platform.
                                        </p>
                                    </div>
                                </div>
                            </section>

                            {/* 3. HOW IT WORKS */}
                            <section className="mb-10">
                                <h2 className="text-2xl font-bold text-slate-900 mb-6 flex items-center gap-3">
                                    <span className="flex items-center justify-center w-8 h-8 rounded-lg bg-[#005081] text-white text-sm font-bold">3</span>
                                    HOW IT WORKS
                                </h2>

                                <div className="space-y-6">
                                    <div>
                                        <h3 className="font-bold text-slate-800 mb-2">3.1</h3>
                                        <p className="text-slate-700 leading-relaxed">
                                            Lohakart provides independent, dynamic and anonymous online platform for the purchase and sale of metal and related products. We are business-to-business and business to customer platform.
                                        </p>
                                    </div>

                                    <div className="bg-green-50 p-6 rounded-xl border border-green-200">
                                        <h3 className="font-bold text-green-900 mb-3 flex items-center gap-2">
                                            <Shield className="w-5 h-5" />
                                            Return & Refund Policy (3.5)
                                        </h3>
                                        <p className="text-sm text-green-800 mb-3">
                                            Lohakart shall entertain return requests only for:
                                        </p>
                                        <ul className="text-sm text-green-800 space-y-2 list-disc list-inside">
                                            <li>Product(s)/goods being damaged</li>
                                            <li>Manufacturing or inherent defect in the product delivered</li>
                                            <li>Product delivered is not the product ordered</li>
                                        </ul>
                                        <p className="text-sm text-green-800 mt-3">
                                            <strong>Important:</strong> Return requests must be placed within 24 hours of delivery. Refund may take up to 30 business days.
                                        </p>
                                    </div>

                                    <div className="bg-blue-50 p-6 rounded-xl border border-blue-200">
                                        <h3 className="font-bold text-blue-900 mb-3 flex items-center gap-2">
                                            <ScrollText className="w-5 h-5" />
                                            Cancellation and Amendment (3.6)
                                        </h3>
                                        <p className="text-sm text-blue-800">
                                            Cancellation or amendment requests can be made only within <strong>24 hours</strong> of placing the order and before confirmation by the Seller. All requests are subject to Lohakart's discretion.
                                        </p>
                                    </div>
                                </div>
                            </section>

                            {/* Key Sections Summary */}
                            <div className="grid md:grid-cols-2 gap-6 my-12">
                                <div className="bg-slate-50 p-6 rounded-xl border border-slate-200">
                                    <h3 className="font-bold text-slate-900 mb-3">4. PRIVACY</h3>
                                    <p className="text-sm text-slate-700">
                                        Your information is governed by our Privacy Policy. We collect, use, and disclose information in accordance with applicable laws and our privacy commitments.
                                    </p>
                                </div>

                                <div className="bg-slate-50 p-6 rounded-xl border border-slate-200">
                                    <h3 className="font-bold text-slate-900 mb-3">5. CONDITIONS</h3>
                                    <p className="text-sm text-slate-700">
                                        Users must be 18+ years old. Provide accurate information. Comply with all applicable laws and regulations.
                                    </p>
                                </div>

                                <div className="bg-slate-50 p-6 rounded-xl border border-slate-200">
                                    <h3 className="font-bold text-slate-900 mb-3">8. INDEMNITY</h3>
                                    <p className="text-sm text-slate-700">
                                        Users agree to indemnify and hold harmless Lohakart from any claims arising from breach of these Terms or unlawful use of the Platform.
                                    </p>
                                </div>

                                <div className="bg-slate-50 p-6 rounded-xl border border-slate-200">
                                    <h3 className="font-bold text-slate-900 mb-3">9. INTELLECTUAL PROPERTY</h3>
                                    <p className="text-sm text-slate-700">
                                        All content, trademarks, and IPR on the Platform belong to Lohakart. Unauthorized use is prohibited.
                                    </p>
                                </div>
                            </div>

                            {/* Important Legal Sections */}
                            <section className="mb-10">
                                <h2 className="text-2xl font-bold text-slate-900 mb-6">Limitation of Liability</h2>
                                <div className="bg-red-50 p-6 rounded-xl border-l-4 border-red-500">
                                    <p className="text-sm text-red-900 leading-relaxed">
                                        <strong>Section 11:</strong> In no event shall the total aggregate liability of Lohakart to any User exceed <strong>INR 1,000</strong> (Indian Rupees One Thousand only). The Platform is provided on an "AS IS" and "AS AVAILABLE" basis. Any claim must be asserted within <strong>SIX (6) months</strong> after the cause of action arose.
                                    </p>
                                </div>
                            </section>

                            <section className="mb-10">
                                <h2 className="text-2xl font-bold text-slate-900 mb-6">Governing Law & Dispute Resolution</h2>
                                <div className="bg-purple-50 p-6 rounded-xl border border-purple-200">
                                    <p className="text-sm text-purple-900 leading-relaxed mb-3">
                                        <strong>Section 16:</strong> These Terms are governed by the laws of India. The courts of <strong>Lucknow, Uttar Pradesh</strong> have exclusive jurisdiction.
                                    </p>
                                    <p className="text-sm text-purple-900 leading-relaxed">
                                        Disputes shall be attempted to be resolved through mutual consultations. If unresolved within 45 days, the matter shall be referred to binding arbitration under the Arbitration & Conciliation Act 1996, with the seat and venue at Lucknow, Uttar Pradesh, India.
                                    </p>
                                </div>
                            </section>

                            {/* Contact Information */}
                            <section className="mb-10">
                                <h2 className="text-2xl font-bold text-slate-900 mb-6">Grievance Officer</h2>
                                <div className="bg-slate-100 p-6 rounded-xl border border-slate-300">
                                    <p className="text-sm text-slate-700 mb-4">
                                        If you have any questions, concerns, or complaints regarding the Platform, Services, or these Terms, you may contact our designated Grievance Officer:
                                    </p>
                                    <div className="space-y-2 text-sm">
                                        <p><strong className="text-slate-900">Name:</strong> <span className="text-slate-700">Belal Ahmad</span></p>
                                        <p><strong className="text-slate-900">Email:</strong> <a href="mailto:business@lohakart.com" className="text-[#be1800] hover:underline">business@lohakart.com</a></p>
                                        <p><strong className="text-slate-900">Address:</strong> <span className="text-slate-700">Levana Cyber Heights, 10 floor, TCG2/2 & 5/5, Vibhuti Khand, Gomti Nagar, Lucknow, Uttar Pradesh 226010, India</span></p>
                                    </div>
                                </div>
                            </section>

                            {/* Final Notice */}
                            <div className="mt-12 p-6 bg-gradient-to-r from-[#005081]/10 to-[#be1800]/10 rounded-xl border border-slate-200">
                                <p className="text-center text-sm text-slate-700">
                                    By using the Lohakart platform, you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions. For the complete and detailed terms, please contact us at <a href="mailto:business@lohakart.com" className="text-[#be1800] hover:underline font-semibold">business@lohakart.com</a>
                                </p>
                            </div>
                        </div>
                    </motion.div>
                </div>
            </main>

            <Footer />
        </div>
    );
}
